---
java_package: openjdk-17-jdk

tomcat_package: tomcat
tomcat_service: tomcat
tomcat_port: 8080
tomcat_enable: true
tomcat_state: started

tomcat_home: /var/lib/tomcat
tomcat_conf: /etc/tomcat

tomcat_user: tomcat
tomcat_group: tomcat
